### ISSUE TITLE
[Fabric] BYG tools are not able to break modded blocks

### ISSUE THREAD

**Issue by Technici4n** [CorgiTaco/BYG#258] opened 2021-01-19 13:56 UTC
It seems BYG tools are not able to break some modded blocks. You should add them to the `fabric:pickaxe` et al tool tags.
See the end of [the wiki page](https://fabricmc.net/wiki/tutorial:mining_levels#making_a_custom_tool).

Should fix TechReborn/TechReborn#2329.

__**API/Modloader**__
Fabric.

_**Steps to reproduce**_
Try to break TR ores with BYG tools (I think).

**Comment by CorgiTaco** [comment] 2021-01-25 21:12
Im gonna say this is a duplicate of #187. So keep an eye on that

**Closed as completed by CorgiTaco** 2021-01-25 21:12 UTC
Labels: Bug Minor, Duplicate, Fabric
