### ISSUE TITLE
BYG 1.1.5 for Fabric breaks vanilla bookshelf (1.1.4 is ok)

### ISSUE THREAD

**Issue by Danklor** [CorgiTaco/BYG#295] opened 2021-02-11 01:02 UTC
Launcher: MultiMC 0.6.11-1370 on MacOS 10.14.6
MC 1.16.5
Fabric loader 0.11.1, API 0.30.0+1.16
BYG 1.1.5 (earlier versions of BYG are not affected by this issue)
duplicated with all other mods removed

When placing a vanilla bookshelf in survival, the item is not removed from inventory. In either survival or creative mode the block is placed in the world, but is invisible. It will only appear on world reload or on a neighboring block update event.

This can be duplicated immediately upon creating a new world and, for me at least, occurs every time a bookshelf is placed. No other factors are needed to produce the issue.

Normally any placed bookshelf is not invisible.

This issue does not cause any entries in the logs nor does it crash the game. Enchanting continues to work as expected.

**Comment by Danklor** [comment] 2021-02-11 12:14
Also of note, repeated placing and breaking bookshelves allows the infinite duplication of books since the bookshelf item is not consumed on placement.

**Comment by what56** [comment] 2021-02-21 13:24
you also can't use bookshelves for enchanting as the table doesn't register the Blocks even if they're made visible by placing and breaking a block next to them (that makes them visible again). it also happens if the bookshelf is placed before installing BYG
although BYG bookshelves work for enchanting.

**Comment by Fourmisain** [comment] 2021-03-13 14:00
I was wondering why this was happening to me, turns out that I had BYG (1.1.6) on my client but not on my server.
After installing BYG on the server, the issue seems to have disappeared - still, it shouldn't happen either way.

For what's it worth, I can't reproduce the issue in singleplayer.

**Comment by CorgiTaco** [comment] 2021-03-15 05:02
FIxed in latest

**Closed as completed by CorgiTaco** 2021-03-15 05:02 UTC
Labels: Bug Minor, Fabric
