### ISSUE TITLE
[1.16.2 Fabric] Blocks don't replace BYG short grass

### ISSUE THREAD

**Issue by artisjoke** [CorgiTaco/BYG#150] opened 2020-10-31 13:10 UTC
You can easily place blocks on vanilla minecraft grass, and the block will replace the grass. BYG short grass, however, won't be replaced, and the block is then placed next to (or on top of) the grass block.

**Comment by Ecorous** [comment] 2020-10-31 16:23
I can confirm

**Comment by CorgiTaco** [comment] 2020-10-31 16:47
What version of BYG?

**Comment by Ecorous** [comment] 2020-10-31 17:02
All that I know Sent from Mail for Windows 10 From: Corgi TacoSent: 31 October 2020 16:48To: CorgiTaco/BYGCc: Expora09; CommentSubject: Re: [CorgiTaco/BYG] [1.16.2 Fabric] Blocks don't replace BYG short grass (#150) What version of BYG?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CorgiTaco** [comment] 2020-10-31 17:03
@Expora09 Uhhh what

**Comment by Ecorous** [comment] 2020-10-31 17:05
oof I tried to reply to the email, I said all that I've played with (the latest)

**Comment by Ecorous** [comment] 2020-10-31 17:09
@CorgiTaco/BYG  Sent from Mail for Windows 10 From: Corgi TacoSent: 31 October 2020 17:04To: CorgiTaco/BYGCc: Expora09; MentionSubject: Re: [CorgiTaco/BYG] [1.16.2 Fabric] Blocks don't replace BYG short grass (#150) @Expora09 Uhhh what—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CorgiTaco** [comment] 2020-10-31 17:25
I cant seem to recreate the bug mentioned here. Considering you said 1.16.2, our latest version is only supported on 1.16.3 and I've just tested that it works. This is also a duplicate of #85 . Here's me placing a block in latest byg(1.1):https://imgur.com/xV8E4iH

**Closed as completed by CorgiTaco** 2020-10-31 17:25 UTC
Labels: Duplicate, Invalid Version, Won't Fix, Fabric
