### ISSUE TITLE
Textures for plant + pot not working as expected 

### ISSUE THREAD

**Issue by Xyclade** [CorgiTaco/BYG#220] opened 2021-01-01 20:20 UTC
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
Reproducable with only Forge + BYG

__**API/Modloader**__
Forge 1.16.4-35.1.13.jar

__**Describe the bug**__

1. When taking a Flower pot, and planting a plant from BYG in there, it results in the following texture in Single player:
![image](https://user-images.githubusercontent.com/3858419/103445520-51ab5680-4c75-11eb-9cf3-0a31b4ee89a1.png)

2. When someone does above on a server, the pot and plant disappear.

__**To Reproduce**__

Local issue:
Take a Flower pot, place in the world

**Expected behavior**
Either the plant ends nicely in the flower pot with the proper texture, or the pot stays where it is and the plant simply does not go in

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.
![image](https://user-images.githubusercontent.com/3858419/103445520-51ab5680-4c75-11eb-9cf3-0a31b4ee89a1.png)

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog -  
Debug.log -  https://paste.ee/p/Zvrwm
Latest.log -  https://paste.ee/p/S4Wqu

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by Xyclade** [comment] 2021-01-01 20:30
Additionally:
Creating a Server with Dynmap + ByG  Results in a hard crash. I've reported https://github.com/webbukkit/dynmap/issues/3231 for that in the Dynmap Repo

**Comment by saltyseadoggo** [comment] 2021-01-01 22:08
> Additionally:
> Creating a Server with Dynmap + ByG Results in a hard crash. I've reported [webbukkit/dynmap#3231](https://github.com/webbukkit/dynmap/issues/3231) for that in the Dynmap Repo

You should make an entirely new bug report for this separate issue so it can be noticed more readily.

**Comment by Xyclade** [comment] 2021-01-01 22:32
@saltyseadoggo I'd expect it to be an issue on the Dynmap side, thats why I refrained from posting it as a bug here. Depending on what the Dynmap engineers say I'll post it as a separate issue 😄

**Comment by CorgiTaco** [comment] 2021-01-02 00:03
Duplicate of #179

**Closed as completed by CorgiTaco** 2021-01-02 00:03 UTC
Labels: Bug Minor
