### ISSUE TITLE
[Bug]: unable to disable the biomepedia of the inventory during the first connection

### ISSUE THREAD

**Issue by ComeBelin** [CorgiTaco/BYG#921] opened 2022-08-20 07:47 UTC
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Bug Severity

Minor

### What happened?

despite the changes made to the configurations, the biomepedia remains in the inventory during the first connection 

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9386460/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by AgPh0enix** [comment] 2022-09-04 20:57
Was this the option referred to above (in biomepedia.json5)?
```
// Whether the biomepedia button is enabled or not in the player inventory for all users connected to this host.
"inventory_enabled": false
```
Or maybe this one (in biomepedia_inventory.json5)?
```
/* Whether the biomepedia button is visible in the player inventory.
   Servers can disable this button from functioning regardless of this value.
*/
"visible": false
```
In either case, the option is only to disable the Biomepedia button, not the item in the starting inventory.  It sounds like the real problem is that **there is no option** to remove the Biomepedia starting item.  This is an important config option for modpack authors, since many of us prefer a clean starting inventory.

**Comment by MokahTGS** [comment] 2022-09-10 18:59
Yes, please fix this!!

**Comment by whatthedrunk** [comment] 2022-09-16 12:59
Yeah this bug is very annoying

**Comment by CorgiTaco** [comment] 2022-10-10 03:14
@johnsone751 Datapacks allow you to disable the advancement which gives the starting item: https://github.com/AllTheMods/ATM-7/blob/main/kubejs/data/byg/advancements/biomepedia_gift.json

**Comment by CorgiTaco** [comment] 2022-10-10 03:18
https://user-images.githubusercontent.com/66983020/194794675-a69422e1-754e-4ab9-a3a0-2943efc7e47e.mp4

I cannot reproduce any of the mentioned issues as seen in this video, therefore closing this.

**Closed as not planned by CorgiTaco** 2022-10-10 03:18 UTC
Labels: Forge, Bug, 1.18

**Comment by CorgiTaco** [comment] 2022-10-10 03:23
The inventory item gift on world first join/load can be removed via this datapack: 
[no_biomepedia.zip](https://github.com/AOCAWOL/BYG/files/9743205/no_biomepedia.zip)
