### ISSUE TITLE
Nether Generation changes after reloading and re-entering world

### ISSUE THREAD

**Issue by GamerGaven** [CorgiTaco/BYG#428] opened 2021-04-27 03:22 UTC
__**API/Modloader**__
1.16.5 Forge 36.1.3

__**Describe the bug**__
The Nether will not generate properly when re-entering newly created world.

__**To Reproduce**__
Create a new world with only BYG installed.
Create a portal and enter the Nether.
Fully exit out of game.
Re-enter the same world and explore new chunks.

**Expected behavior**
For the Nether to generate according to seed (or however the Nether generation is determined).

**Screenshots/Videos**
Creating a new world and entering the Nether. 
https://streamable.com/8y21lr

Re-entering world and showing off generation issue.
https://streamable.com/jh78b9

**Additional context**
This was re-created on a newly loaded forge install and without tampering with configs. Only mod installed was BYG.

**Logs**
Crashlog - None
Link to debug and logs:
https://paste.ee/p/Q0R9o

**Comment by CorgiTaco** [comment] 2021-05-05 04:48
Duplicate of #309

**Closed as completed by CorgiTaco** 2021-05-05 04:48 UTC
Labels: Bug Major
