### ISSUE TITLE
[1.19][Crash]:  "byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part.

### ISSUE THREAD

**Issue by CKY-** [CorgiTaco/BYG#1206] opened 2023-06-15 22:53 UTC
### BYG Version

2.0.1.3

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### Bug Severity

Major

### What happened?

go to the end 
/locate bioem byg:imparius
and teleport
nothing is generated in the area with no other mods installed 

this mod stack is 

CorgiLib
Corgi_Taco
CorgiLib-forge-1.19.2-1.0.0.34.jar
[https://www.curseforge.com/minecraft/mc-mods/corgilib](https://www.curseforge.com/minecraft/mc-mods/corgilib)

GeckoLib
Gecko
geckolib-forge-1.19-3.1.40.jar
[https://www.curseforge.com/minecraft/mc-mods/geckolib](https://www.curseforge.com/minecraft/mc-mods/geckolib)

Oh The Biomes You'll Go
AOCAWOL
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.3.jar
[https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)

TerraBlender (Forge)
TheAdubbz
TerraBlender-forge-1.19.2-2.0.1.136.jar
[https://www.curseforge.com/minecraft/mc-mods/terrablender](https://www.curseforge.com/minecraft/mc-mods/terrablender
)

go to the end 
/locate bioem byg:imparius
and teleport

Crash 
 "byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part.
this mod stack is 

Farmer's Delight
vectorwing
FarmersDelight-1.19-1.2.1.jar
[https://www.curseforge.com/minecraft/mc-mods/farmers-delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)

CorgiLib
Corgi_Taco
CorgiLib-forge-1.19.2-1.0.0.34.jar
[https://www.curseforge.com/minecraft/mc-mods/corgilib](https://www.curseforge.com/minecraft/mc-mods/corgilib)

GeckoLib
Gecko
geckolib-forge-1.19-3.1.40.jar
[https://www.curseforge.com/minecraft/mc-mods/geckolib](https://www.curseforge.com/minecraft/mc-mods/geckolib)

Oh The Biomes You'll Go
AOCAWOL
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.3.jar
[https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)

TerraBlender (Forge)
TheAdubbz
TerraBlender-forge-1.19.2-2.0.1.136.jar
[https://www.curseforge.com/minecraft/mc-mods/terrablender](https://www.curseforge.com/minecraft/mc-mods/terrablender
)

### latest.log

oh the bioems by its self 
https://gist.github.com/CKY-/6ff2c7be4a4263447a132ecc85841a2f
oh the bioems crash 
https://gist.github.com/CKY-/85421e70b89db40057abedfca4279177
oh the bioems with farmers delight 
https://gist.github.com/CKY-/88e337b92c121ef9e350b7062fcd06b0
crash repprt only of oh the bioems and farmers delight 
https://gist.github.com/CKY-/2a44f0637b0fe0943a41f683be45dcb0

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by CKY-** [comment] 2023-06-15 23:00
[config.zip](https://github.com/AOCAWOL/BYG/files/11763849/config.zip)
and here is the config this is a fresh instance created on curseforges launcher to test all of this so no modificants to the configs have been made by me personally

**Comment by m2jest1c** [comment] 2023-06-16 18:18
Reproduced on Fabric; the NBT file in the repo itself is corrupt according to IntelliJ. When a client tries to load it, the server crashes. The end is inaccessible on my servers. 

To simplify, when it's a client w/o a server, nothing loads, and when it's a client with a server, the server crashes and the client is kicked off.

**Comment by maltalented** [comment] 2023-06-16 18:21
Reproduced on Fabric.

**Comment by CameronJThomas** [comment] 2023-06-17 13:30
Just ran into this with Forge. Went through an end portal, instant server crash with `Caused by: java.lang.IllegalArgumentException: "byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part.`

**Comment by CameronJThomas** [comment] 2023-06-17 13:38
As a workaround to avoid crashes, you can disable the generation of this specific biome until it's fixed. In your instance (or server) directory, go to `config` -> `byg` -> `end-biomes.json5` and locate the line which says `"data": "byg:imparius_grove",` (line 66 for me). Immediately underneath, change `"weight": 3` to `"weight": 0` and it will prevent the biome from being generated. You might need to reset your End dimension (delete the `DIM1` folder in your world directory) and restart your game/server for this to work.

**Comment by RoyalWolfie** [comment] 2023-06-17 14:57
also ran into this issue `"Caused by: java.lang.IllegalArgumentException: "byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part."`
and also
[00:31:12] [Worker-Main-4/ERROR]: Failed to light chunk [-76, -113]

**Comment by RoyalWolfie** [comment] 2023-06-17 15:11
> As a workaround to avoid crashes, you can disable the generation of this specific biome until it's fixed. In your instance (or server) directory, go to `config` -> `byg` -> `end-biomes.json5` and locate the line which says `"data": "byg:imparius_grove",` (line 66 for me). Immediately underneath, change `"weight": 3` to `"weight": 0` and it will prevent the biome from being generated. You might need to reset your End dimension (delete the `DIM1` folder in your world directory) and restart your game/server for this to work.

ive tried this and it still crashes.

**Comment by XionioXMaster** [comment] 2023-06-18 07:33
same

**Comment by KeWHs** [comment] 2023-06-18 12:30
ive tried to read the nbt file with NBT viewer in VScode. it cant be opened.

**Comment by digishield** [comment] 2023-06-19 00:35
Hey, guys. I had the same problem and the only thing that helped after about a million tries is to edit the BYG config: 
`end-biomes.json5` 

specifically:

`"addAllEndBiomeCategoryEntries": false`
`"forceBYGEndBiomeSource": false`


In addition, I set all biomes from BYG weight to 0 as already written here. I deleted the DIM1 folder and restarted the server. This achieved that the BYG biome was deactivated and only the Better Nether biome was generated. It's at least some workaround until a fix is found. Hopefully this will help.

**Comment by BoranYEET** [comment] 2023-06-19 12:14
Also ran on the same issue on Fabric 1.19.2: `Caused by: java.lang.IllegalArgumentException: "byg:features/mushrooms/imparius/imparius_mushroom_canopy6" is not a valid tree part.`

**Comment by Alliegaytor** [comment] 2023-06-20 10:14
I just compiled the mod from source on the 1.19.x branch and can confirm this is a bug in the latest commit.

When I try and place the feature I get this:

```
[20:02:56] [Server thread/ERROR] (Minecraft) Couldn't load structure byg:features/mushrooms/imparius/imparius_mushroom_canopy6
 net.minecraft.ReportedException: Loading NBT data
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:514) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:155) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:155) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.ListTag$1.load(ListTag.java:135) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.ListTag$1.load(ListTag.java:135) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:497) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:155) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:155) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:168) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo.java:117) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:52) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.readStructure(StructureTemplateManager.java:237) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.load(StructureTemplateManager.java:233) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.loadFromResource(StructureTemplateManager.java:110) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.tryLoad(StructureTemplateManager.java:95) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.get(StructureTemplateManager.java:84) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at corgitaco.corgilib.world.level.feature.gen.TreeFromStructureNBTFeature.place(TreeFromStructureNBTFeature.java:50) ~[corgilib-1.19.2-1.0.0.34-fabric.jar:?]
	at net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:224) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:26) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.commands.PlaceCommand.placeFeature(PlaceCommand.java:69) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.commands.PlaceCommand.method_39990(PlaceCommand.java:61) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:242) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:1214) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.method_44356(ServerGamePacketListenerImpl.java:1199) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.method_5386(BlockableEventLoop.java:69) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:25) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:29) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:731) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1681) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:716) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:712) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:695) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:631) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:260) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.IOException: Invalid tag id: 116
	at net.minecraft.nbt.TagType$1.createException(TagType.java:38) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
Caused by: java.io.IOException: Invalid tag id: 116

	at net.minecraft.nbt.TagType$1.load(TagType.java:38) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.TagType$1.load(TagType.java:38) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:497) ~[minecraft-merged-project-@fabric-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar:?]
	... 40 more
[20:02:56] [Render thread/INFO] (Minecraft) [System] [CHAT] An unexpected error occurred trying to execute that command
[20:02:57] [Server thread/INFO] (Minecraft) Saving and pausing game...
[20:02:57] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[20:02:57] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[20:02:57] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[20:04:42] [Render thread/INFO] (Minecraft) [System] [CHAT] An unexpected error occurred trying to execute that command
```

The game also crashes when it tries to load these mushrooms that naturally spawned in the worldgen.

It seems like [imparius_mushroom_canopy6.nbt](https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/resources/data/byg/structures/features/mushrooms/imparius/imparius_mushroom_canopy6.nbt) is corrupted, but I don't know much about Minecraft modding to know for sure.

**Comment by Alliegaytor** [comment] 2023-06-20 10:20
![2023-06-20-201832_screenshot](https://github.com/AOCAWOL/BYG/assets/61523203/46301929-28af-49bb-9640-39a0682f9a6d)

Ok, I'm 99% sure it's this file causing it. It's the only nbt file that I can't read

**Comment by m2jest1c** [comment] 2023-06-20 10:23
Correct. That was established. I also attempted to compile it myself. It is certainly that file, although what I don't understand is why it's causing issues now but not on the March 7th v2.0.1.1 build, which was released after this file was created. I'm sure decompiling 2.0.1.1 would explain that, but I'm too lazy and it doesn't really matter.

Did I mention? Best fix for the time being is just to go back to an older version.

Forge: https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-forge
Fabric: https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-fabric

**Comment by Alliegaytor** [comment] 2023-06-20 11:41
> Correct. That was established. I also attempted to compile it myself. It is certainly that file, although what I don't understand is why it's causing issues now but not on the March 7th v2.0.1.1 build, which was released after this file was created. I'm sure decompiling 2.0.1.1 would explain that, but I'm too lazy and it doesn't really matter.
> 
> Did I mention? Best fix for the time being is just to go back to an older version.
> 
> Forge: https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-forge Fabric: https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-fabric

Thanks for sending those links. I've got it working locally with the nbt file from that jar. For some reason the compiled version had the working nbt file, but the git repo doesn't.

I tried to commit the file to a fork I just made, but for some reason git doesn't want to add the file no matter what I do. I get

`
warning: in the working copy of 'Common/src/main/resources/data/byg/structures/features/mushrooms/imparius/imparius_mushroom_canopy6.nbt', CRLF will be replaced by LF the next time Git touches it
`
and it vanishes from git? I'm wondering if something similar happened here causing the file to be out of sync.

Hopefully someone better at git can sort this out, as the fix is rather trivial but escapes me -_-

**Comment by FatalityWar** [comment] 2023-06-20 11:41
Thanks everyone for the discussion, I tried calling the BetterEnd dev and he helped a lot, and found that the imparius_grove files are corrupt, this trade was very helpful for everyone!

**Comment by m2jest1c** [comment] 2023-06-20 16:48
> > Correct. That was established. I also attempted to compile it myself. It is certainly that file, although what I don't understand is why it's causing issues now but not on the March 7th v2.0.1.1 build, which was released after this file was created. I'm sure decompiling 2.0.1.1 would explain that, but I'm too lazy and it doesn't really matter.
> > Did I mention? Best fix for the time being is just to go back to an older version.
> > Forge: https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-forge Fabric: https://modrinth.com/mod/biomesyougo/version/1.19.2-2.0.1.1-fabric
> 
> Thanks for sending those links. I've got it working locally with the nbt file from that jar. For some reason the compiled version had the working nbt file, but the git repo doesn't.
> 
> I tried to commit the file to a fork I just made, but for some reason git doesn't want to add the file no matter what I do. I get
> 
> `warning: in the working copy of 'Common/src/main/resources/data/byg/structures/features/mushrooms/imparius/imparius_mushroom_canopy6.nbt', CRLF will be replaced by LF the next time Git touches it` and it vanishes from git? I'm wondering if something similar happened here causing the file to be out of sync.
> 
> Hopefully someone better at git can sort this out, as the fix is rather trivial but escapes me -_-

The PR I attempted above seemed to go through fine locally, but remotely it seems that git refuses to recognize that there were changes in the file. The hashes are correct locally, but on remote they are the same as the old one. Not sure why that is. I'll see if I can figure out anything before someone else takes a look.

**Comment by CorgiTaco** [comment] 2023-06-22 03:09
Fixed in latest release

**Closed as completed by CorgiTaco** 2023-06-22 03:09 UTC
Labels: Bug, 1.19
