### ISSUE TITLE
Trees Don't Grow

### ISSUE THREAD

**Issue by CeedyBoiii** [CorgiTaco/BYG#636] opened 2022-02-09 01:10 UTC
__**API/Modloader**__
Forge

__**Describe the bug**__
Saplings do not grow at all. Bonemeal does not work either. All saplings in BYG alone are affected by this.

__**To Reproduce**__
Attempt to grow a tree using saplings and bonemeal, or waiting for it to naturally grow.

__**Expected behavior**__
The sapling was expected to grow into a tree, but it did not.

**Comment by CorgiTaco** [comment] 2022-02-09 03:50
Ensure you are using the latest version of byg. Duplicate of #626

**Closed as completed by CorgiTaco** 2022-02-09 03:50 UTC
Labels: Bug Minor

**Comment by CeedyBoiii** [comment] 2022-02-09 04:32
I am for sure using the newest version, 1.3.5.9 for Forge version 1.18.1. (The rest of this mod is absolutely stellar, by the way.)

**Comment by CorgiTaco** [comment] 2022-02-09 04:38
@CeedyBoiii what sapling r  u trying to do

**Comment by CeedyBoiii** [comment] 2022-02-09 04:50
all of them, really. I have a world for charting out block pallets and foliage. I've tried all the sapling patterns as well

**Comment by CorgiTaco** [comment] 2022-02-09 04:51
please join our discord: https://discord.gg/knpP4243

**Comment by CeedyBoiii** [comment] 2022-02-09 04:58
Just joined! my user is Aszellem.
