### ISSUE TITLE
BYG encountered an error during the complete event phase

### ISSUE THREAD

**Issue by aaronhowser1** [CorgiTaco/BYG#266] opened 2021-01-23 09:49 UTC
__**Mod conflict? If so, please clarify which mod is conflicting!**__
*Maybe* quark, somehow?

__**API/Modloader**__
Forge

__**Describe the bug**__
I changed a config in Quark (variant chest recipes to off) and relaunched and got this screen
![image](https://user-images.githubusercontent.com/15698722/105574919-435cd180-5d2d-11eb-898e-e890d522f1d0.png)
Changing the config back to on fixes it, oddly. I've seen this error before and it was fixed by only restarting with no changes, but this one didn't.

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - N/A
Debug.log - [debug.log file](https://github.com/CorgiTaco/BYG/files/5859995/debug.log)
Latest.log - https://pastebin.com/s03pX5qJ

This is using byg-1.1.6

**Comment by CorgiTaco** [comment] 2021-01-23 10:18
Duplicate of #265.

Fixed in latest beta

**Closed as completed** 2021-01-23 10:18 UTC
Labels: Duplicate
