### ISSUE TITLE
[1.19.2][Bug]: Sandstone Recipe is Broken

### ISSUE THREAD

**Issue by Ghastly13** [CorgiTaco/BYG#1210] opened 2023-06-18 04:23 UTC
### BYG Version

2.0.1.3

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Minor

### What happened?

The sandstone recipe is broken. Weird issue, not sure what caused this. The recipe couldn't find "c:sand/*color*". The issue persists with all colors of sand.
Example with other mods enabled (performance mods, bugfix mods, Biomes O' Plenty):
![2023-06-18_00 14 48](https://github.com/AOCAWOL/BYG/assets/83313692/fe139790-2c42-44a9-b1ad-0905792a6f22)
Example with only (and I mean only) BYG enabled:
![2023-06-18_00 18 13](https://github.com/AOCAWOL/BYG/assets/83313692/c175f368-5135-47d3-8cd9-4351fa19d34a)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/11780626/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by Ghastly13** [comment] 2023-06-18 04:23
I'm a novice when it comes to modding Minecraft, so I may have done something wrong here. I apologize in advance!

**Comment by CorgiTaco** [comment] 2023-06-22 03:11
Duplicate of #1204

**Closed as not planned by CorgiTaco** 2023-06-22 03:11 UTC
Labels: Bug, 1.19

**Comment by Raysofdoom2665** [comment] 2023-07-26 04:41
I have this same problem, BYG version 2.0.1.4
