### ISSUE TITLE
[1.15.2] startup crash

### ISSUE THREAD

**Issue by TheGoldenProof** [CorgiTaco/BYG#34] opened 2020-05-18 01:49 UTC
crash report: https://pastebin.com/q5SeBpFP

**Comment by CorgiTaco** [comment] 2020-05-28 04:42
You need to provide more details and additionally does this happen with BYG itself? Or with other mods. This could mean a possible mod conflict.

**Comment by CorgiTaco** [comment] 2020-05-30 02:07
Closing this assuming the issue is resolved

**Closed** 2020-05-30 02:07 UTC
Labels: bug, question
