### ISSUE TITLE
[1.16.4 Forge] Holly sapling in a flower pot = invisble block

### ISSUE THREAD

**Issue by dkbhn** [CorgiTaco/BYG#225] opened 2021-01-02 21:16 UTC
Hi there

If you put a holly sapling in a minecraft flowerpot the whole thing gets invisible, and it looks like there is no block. You cannot place a new block there, and you can't walk through it.

A workaround is to place a cyclic block breaker next to it, and it'll break into a sapling and a pot.

**Comment by CorgiTaco** [comment] 2021-01-02 21:32
Duplicate of #179

**Closed as completed by CorgiTaco** 2021-01-02 21:32 UTC
Labels: Duplicate
