### ISSUE TITLE
[1.19][Bug]: Coloured sandstones cannot be crafted,

### ISSUE THREAD

**Issue by 8BitLimes** [CorgiTaco/BYG#1244] opened 2023-08-31 00:04 UTC
### BYG Version

2.0.1.4

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Bug Severity

Major

### What happened?

None of the coloured sandstones are craftable. The crafting recipes require barrier blocks named "Empty Tag: c:sand/[colour]" where [colour] depends on the type of sandstone. The name of the barrier block implies this is some issue with the block reference for the crafting recipe.
![2023-08-30_19 59 05](https://github.com/AOCAWOL/BYG/assets/56005860/ddb8b51c-497b-45e1-982d-11218082913f)
![2023-08-30_19 59 07](https://github.com/AOCAWOL/BYG/assets/56005860/abee08c2-9e81-4359-b154-02701d3c4e14)
![2023-08-30_19 49 07](https://github.com/AOCAWOL/BYG/assets/56005860/4f51a95b-7127-433a-8886-45f9f74a8acc)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/12480900/latest.log)

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment] 2023-10-23 04:53
Fixed in 82f84129aeac5b5b740a7b72ff24933ea4002693
Duplicate of #1204

**Closed as completed by JT122406** 2023-10-23 04:53 UTC
Labels: Bug, 1.19
