### ISSUE TITLE
[1.16.14] Optifine conflicting with BYG (No trees or plants)???

### ISSUE THREAD

**Issue by young4623** [CorgiTaco/BYG#199] opened 2020-12-15 06:09 UTC
I don't know how but I believe Optifine(FORGE) is conflicting with BYG (FORGE)

Basically, any new land I find, the biomes end up being empty with now trees or foliage. For instance, the tropical fungal jungle biome from BGY is nothing but a field of dirt blocks with no grass mind you. I mean I can still see some trees, but there is absolutely no grass or other plants in non vanilla biomes.

__**To Reproduce**__
Idk what you mean by this.

**Expected behavior**
I expected there to be a trees and plants in the new biomes.

**Screenshots/Videos**

![2020-12-15_00 02 49](https://user-images.githubusercontent.com/76028233/102177505-b131f580-3e71-11eb-87de-6f27dd9c7e29.png)
![2020-12-15_00 02 21](https://user-images.githubusercontent.com/76028233/102177514-b5f6a980-3e71-11eb-8357-319d32f5f41a.png)
![2020-12-15_00 02 41](https://user-images.githubusercontent.com/76028233/102177517-b68f4000-3e71-11eb-95d7-bb7593cd09ca.png)

IDK how to provide logs. I only play the game. Sorry.

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by CorgiTaco** [comment] 2020-12-15 06:10
Duplicate of #198 and #97

**Comment by CorgiTaco** [comment] 2020-12-15 06:11
Also stop reporting things twice please and thanks

**Closed as completed by CorgiTaco** 2020-12-15 06:10 UTC
Labels: Duplicate, Won't Fix, Mod Conflict

**Comment by young4623** [comment] 2020-12-15 12:55
Sorry about that. I wasn't really sure I I sent the first one.
