### ISSUE TITLE
Crash 1.16.2

### ISSUE THREAD

**Issue by Sunekaer** [CorgiTaco/BYG#68] opened 2020-08-14 20:18 UTC
Forge: 33.0.5
byg-1.0.0
https://paste.ee/p/eH7vp

**Comment by CorgiTaco** [comment] 2020-08-14 20:49
I can't reproduce this crash

**Comment by Sunekaer** [comment] 2020-08-14 22:42
I didn't get the crash on first world creation, i got it after flying around and generating biomes

So I disabled all other mods, and did the same thing, fly around and crashed 

https://paste.ee/p/VQqiE

**Comment by CorgiTaco** [comment] 2020-08-15 01:17
Try using a lower forge version

**Comment by Sunekaer** [comment] 2020-08-15 08:58
Due to netherportals being broken in older versions i cant.

```
Build: 1.16.2-33.0.5 - Fri Aug 14 19:05:15 GMT 2020
	lex:
		Fix creating nether portals.

	lex:
		New method for creating modded tag references, fix connecting to vanilla servers.

=========
Build: 1.16.2-33.0.3 - Fri Aug 14 02:17:01 GMT 2020
	43609023+spnda:
		Print mod file name on InvalidModFileException (#7241)

=========
Build: 1.16.2-33.0.2 - Thu Aug 13 19:26:22 GMT 2020
	cyborgmas18:
		Fix server connection, misapplied patch (#7245)

	Yunus1903:
		Updated MDK and README for 1.16.2 (#7243)

=========
Build: 1.16.2-33.0.0 - Thu Aug 13 07:37:04 GMT 2020
	lex:
		Initial 1.16.2 Update

```

**Comment by CorgiTaco** [comment] 2020-08-15 08:59
Give me the seed of the world that crashes, approximate coordinates, and what direction you go from spawn

**Comment by Sunekaer** [comment] 2020-08-15 14:12
Seed:
8061561287747858956

Spawn:
![image](https://user-images.githubusercontent.com/18720460/90314150-c9b8f000-df11-11ea-831e-0f64c7f162a0.png)

Headin:
South

Crashed at:
173, 64, 1111

log: 
https://paste.ee/p/fGO62

**Comment by Sunekaer** [comment] 2020-08-15 14:16
Crash on world creation

Seed:
-8776259588245163725

https://paste.ee/p/KUbsV

**Comment by CorgiTaco** [comment] 2020-08-16 01:51
Try the new jar I uploaded. I apparently fixed it for someone else by doing nothing

**Comment by Sunekaer** [comment] 2020-08-16 09:00
Seems better so far

**Comment by CorgiTaco** [comment] 2020-08-16 09:02
I'm going to close this issue then, if it reappears open it back up/comment

**Closed as completed** 2020-08-16 09:02 UTC
Labels: Bug Minor
