### ISSUE TITLE
BYG 1.1.5 crashes with BetterEnd

### ISSUE THREAD

**Issue by LuamLeite** [CorgiTaco/BYG#297] opened 2021-02-11 21:35 UTC
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**
Hello, I tried to update BYG from 1.13 to 1.15 and started conflicting with BetterEnd, 1.13 was fine.
I even left just byg-1.1.5, fabric-api and BetterEnd in my mods folder to test it.

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
BetterEnd 0.88

__**API/Modloader**__
Fabric

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
When launching the game, it just crashes :(
__**To Reproduce**__
Have BetterEnd 0.88 and byg-1.1.5 for fabric in the mods folder, I use fabric api-0.29.3 and Minecraft 1.16.4

**Expected behavior**
Both to run ok

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog -  https://pastebin.com/Lv7PTLNM
Debug.log - Debug.log is not being updated for some reason.
Latest.log - https://pastebin.com/rvQdpag3

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment] 2021-02-11 22:14
4th one in a row...... Duplicate of #296 #294 #293

**Closed as completed by CorgiTaco** 2021-02-11 22:14 UTC
Labels: Duplicate, Won't Fix, Mod Conflict
