### ISSUE TITLE
Entire Forests Not Generating

### ISSUE THREAD

**Issue by KamikazePigeon** [CorgiTaco/BYG#241] opened 2021-01-10 10:13 UTC
Using the latest version of Forge and BYG. Some problems of this issue COULD be mod conflicts, but not all of them. As far as I know, a mod conflict shouldn't remove entire types of wood from the game/creative inventory (maybe I'm wrong, do tell me if I am, lol).

Sometimes entire biomes do not generate as they should, instead leaving giant expanses of empty land. At first we thought it was a simple mod conflict (which for some of them it may very well be, but not for all of them). I tried to collect as much different types as I could find for more data. I checked with both my minimap mod (which tells the biome I'm in) and the F3 menu. Always the same issue; large expanses of land completely empty of trees that SHOULD by all means generate (ie. no trees whatsoever in a BYG Rainforest biome).

At first I assumed the trees were being forced not to generate by a mod, but then when I checked in the creative inventory, I found entire sections of tree blocks missing completely, such as the Red Oak Wood and Deciduous Wood (which would explain why there would be no forests of these two tree types). However, for others, such as Jacaranda Forests, there ARE wood types for them, and I do think that could be a mod conflict. 
Let me know if you want the list of mods, I don't have it on-hand currently but I can get it if needed.

To reproduce:
Make a world. Find a Red Oak Forest. Behold the "forest".

![2021-01-07_23 23 03](https://user-images.githubusercontent.com/75771054/104119985-5365c180-52e8-11eb-8c08-ed3960092cb0.png)
![2021-01-07_23 23 12](https://user-images.githubusercontent.com/75771054/104119990-58c30c00-52e8-11eb-96c9-bb0524867dcd.png)
![2021-01-07_23 22 39](https://user-images.githubusercontent.com/75771054/104119997-637da100-52e8-11eb-84b2-1b3243220e7f.png)
![2021-01-08_00 09 44](https://user-images.githubusercontent.com/75771054/104119998-65476480-52e8-11eb-8036-ab099ecdbc57.png)
![2021-01-08_00 07 42](https://user-images.githubusercontent.com/75771054/104120004-69738200-52e8-11eb-8993-99a97b76107b.png)

This is the only tree type I saw that is most likely a mod conflict, unless there never was a tree structure added for the Jacaranda Tree.
![2021-01-07_23 43 10](https://user-images.githubusercontent.com/75771054/104120006-6d9f9f80-52e8-11eb-86de-d3e3e1671158.png)
![2021-01-07_23 43 02](https://user-images.githubusercontent.com/75771054/104120012-73958080-52e8-11eb-9c40-6c646b3f7f3b.png)

Found a Deciduous Forest and forgot to get a picture until after I left it, but there's no wood for the trees there. 
![2021-01-07_23 36 26](https://user-images.githubusercontent.com/75771054/104120010-71cbbd00-52e8-11eb-9272-1aa422eddfad.png)

**Comment by moon-st0ne** [comment] 2021-01-10 22:25
well, red oak trees just have vanilla oak wood, so that's not the issue here. i think this latest version just has a horrible generation bug.

**Comment by CorgiTaco** [comment] 2021-01-10 22:26
Both of you are wrong, this is a duplicate of #97. You need to use the latest version of optifine

**Closed as completed by CorgiTaco** 2021-01-10 22:26 UTC
Labels: Duplicate
