### ISSUE TITLE
[1.16.4] optifine causes trees and foliage to not spawn???

### ISSUE THREAD

**Issue by young4623** [CorgiTaco/BYG#198] opened 2020-12-15 05:48 UTC
I disabled some mods on FORGE and I think Optifines is somehow conflicting with terrain generation on BYG.

Bug: Every time I enter a BYG biome, there are no trees or plants. Just dirt. There isn't even a biome.
 
I expected there to be trees or plants in a biome that's supposed to be a jungle or a forest.

Here are some screenshots
![2020-12-15_00 02 49](https://user-images.githubusercontent.com/76028233/102176241-04567900-3e6f-11eb-8d80-c4410c86e371.png)
![2020-12-15_00 02 41](https://user-images.githubusercontent.com/76028233/102176248-06b8d300-3e6f-11eb-8494-de53b8b18d03.png)
![2020-12-15_00 02 21](https://user-images.githubusercontent.com/76028233/102176256-09b3c380-3e6f-11eb-9980-94112412db08.png)

I'm not sure how to provide any logs. I just play the game.

Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
Debug.log - 
Latest.log -

**Comment by CorgiTaco** [comment] 2020-12-15 05:50
Duplicate of #97 BYG & every other world generation mod in versions 1.16.2+ will break when Optifine shaders are active on forge. A workaround for this issue is to turn off shaders when loading your game/into a world and re-enable shaders AFTER entering your world.

**Closed as completed by CorgiTaco** 2020-12-15 05:50 UTC
Labels: Duplicate, Won't Fix, Mod Conflict
