### ISSUE TITLE
Embur Bog kills the Lighting Thread In ATM6

### ISSUE THREAD

**Issue by 0mega420** [CorgiTaco/BYG#112] opened 2020-10-10 06:41 UTC
so here at All the Mods team on ATM6 1.16.3 modpack version 1.1.1 there is a huge leak when players get near an ember bog, in order to get the server to run chunks had to be unloaded....the fix was to just remove the embur biome in the config and reset the nether. this solves the problem...for now

**Comment by CorgiTaco** [comment] 2020-10-10 06:44
Please provide a heap dump to back this statement. You're probably going on about the Light manager NPE that is known and this can simply be fixed with a server restart.

**Comment by CorgiTaco** [comment] 2020-10-10 06:46
And have you ran BYG on its own to ensure this is the case?

**Comment by CorgiTaco** [comment] 2020-10-12 01:52
From DMs: 

> ATM6 heap dump while standing in Embur Bog biome: https://drive.google.com/file/d/1jR5rSqzMiyFEDP9vOkwuo7UXw51IcBV7/view?usp=sharing
Seems to be GC lag from maxing out the heap. I tested with just BYG and the heap stays around 3.3 GB and doesn't increase further. So I guess it's probably some sort of mod interaction.

**Comment by TelepathicGrunt** [comment] 2020-10-13 04:22
Do you have a seed and coordinate to an Ember Bog with ATM6 on? I have tried ATM6 1.1.3b and 1.1.2 and can't find a bog lol

**Comment by CorgiTaco** [comment] 2020-10-13 04:25
uhhhh should just be any world.....

**Comment by CorgiTaco** [comment] 2020-10-13 04:27
oh wait they disabled it, youll need to add it to the list of nether biomes. byg:embur_bog

**Comment by CorgiTaco** [comment] 2020-10-30 04:54
Closing this issue as it can't be recreated and if anything, should be patched in our latest versions. Comment back here if the issue persists

**Comment by nobotious** [comment] 2020-12-27 08:14
Having something like this going on, running version 1.3.7 of all the mods 6. profiling is pointing me towards high cycle usage by bees pathing (pack runs resourceful bees), but only seems to happen when an ember bog biome is near / player is in one. will play around more tomorrow and see if I can reproduce more. could definitely be weird mod interaction.

**Comment by Raderg** [comment] 2021-01-03 16:30
Closest nether fortress is on an embur bog. Everytime I get close to it memory usage goes to the roof, game freezes up for a while and ends up crashing. If you tell me what to look for I can do some tests.

**Comment by Ruchian** [comment] 2021-01-05 10:14
I was discussing it here in my own issue
https://github.com/AllTheMods/ATM-6/issues/719

I have a bit of a hint I found at least.
I noticed that the biome itself doesn't do much on its own. So long it doesn't involve any entity with fire on it. (blaze, lava bees.)
Something weird seems to happen when a single blaze even spawns there for some reason. (blame Quark, Vazkii)
If you kill the blaze before it has much chance to do anything you'll be fine for a moment, but... yeah, this is eventually what causes the whole crash issue, in my observation at least.

What is supposed to happen when Fire is present in the Embur Bog biome?

**Comment by CorgiTaco** [comment] 2021-01-05 10:22
Ngl i suspicion the issue lies with the embur gel which speeds any entities on it up to really high speeds. So I can imagine entities are launched into un generated chunks. We're toning it down in this week's patch so yeah

**Comment by CorgiTaco** [comment] 2021-01-05 23:13
Try this: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/3159758

**Comment by Raderg** [comment] 2021-01-06 00:40
This fixes it for me. I've been roaming the zone where the issues appeared almost instantly for about 20 min now and runs perfectly.

**Closed as completed** 2021-01-06 01:35 UTC
Labels: Requires Information, Bug Major, Forge, Help Wanted
