### ISSUE TITLE
[Forge - 1.16.4] Forests without trees

### ISSUE THREAD

**Issue by Allomere** [CorgiTaco/BYG#189] opened 2020-12-12 01:07 UTC
Today i decided to update my private modpack to 1.16.4 since most mods had a working build for that version, i createad a new world to do some troubleshooting and verify if everything was working as intended, but i noticed that the biomes were a little to "plane" and realised that most of the forests from BYG aren't generating with trees.
I unistalled all the mods that affected world generation, leaving only optfine, byg and minimap that shows my current biome.

And when i created a new wolrd i spawned on a Seasonal Forest biome and imeadtly noticed the lack of trees and folliages:
![image](https://user-images.githubusercontent.com/71918599/101968180-8ee37200-3bfc-11eb-9bc8-8fabba54fe61.png)
I looked for posts related to this issue but i couldnt find any, is this a known bug ?

**Comment by CorgiTaco** [comment] 2020-12-12 01:09
Remove optifine(all world gen mods are ruined by optifine fyi). Duplicate of #97

**Closed as completed by CorgiTaco** 2020-12-12 01:09 UTC
Labels: Duplicate, Won't Fix, Mod Conflict
