### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by timtornado** [CorgiTaco/BYG#811] opened 2022-06-11 19:44 UTC
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

0.14.7

### What happened?

places witch hazel sign and crashed now anyone that gets near it crashes

### crash-log

1.1.0.102.jar

### latest.log

https://paste.ee/p/JVonS

**Comment by itsallybear** [comment] 2022-06-12 01:14
I, too, am having this issue with a Witch Hazel sign.
[crash2.txt](https://github.com/AOCAWOL/BYG/files/8884987/crash2.txt)

**Comment by itsallybear** [comment] 2022-06-12 01:19
Here is my temporary fix: 

If you know someone who has access to the console, log in to the area that is crashing players, and quickly have them use the /setblock command to delete the block using coordinates mentioned in your crash report, which you can find in the Block Location field under the -- Block Entity Details -- heading. 

Hope this helps.

**Comment by CorgiTaco** [comment] 2022-06-12 19:49
Duplicate of #810

**Closed as not planned by CorgiTaco** 2022-06-12 19:49 UTC
Labels: Bug Major, Bug
