### ISSUE TITLE
Bookshelves are invisible and prevent enchanting upgrades [1.16.5]

### ISSUE THREAD

**Issue by HoneyBadger1337** [CorgiTaco/BYG#317] opened 2021-02-23 21:29 UTC
__**Mod conflict? If so, please clarify which mod is conflicting!**__
Not a mod conflict. Tested by itself and the issue still occurred

__**API/Modloader**__
Fabric

__**Describe the bug**__
When placing bookshelves, they are invisible until you break one _adjacent_ to one another or wait for it to eventually appear. It also prevents trying to upgrade the enchanting table (You can still use it, but you won't get anything past Tier II even with bookshelves surronuding it)

Also, no noise is made when placing down

Another thing: You have an infinite amount of bookshelves to place down, whether it's 1 or 64, you can basically get infinite amount of books

__**To Reproduce**__

Invisible bookshelf - Place bookshelf

Enchanting table - Surround bookshelf with bookshelves, and attempt to upgrade past Tier II

**Expected behavior**
Bookshelves to appear after placing down and enchanting tables to be upgraded as appropriate when surrounded by bookshelves

**Screenshots/Videos**

Youtube video detailing the issue:
https://www.youtube.com/watch?v=PeG46fBFJsQ&feature=youtu.be

**Additional context**
N/A

**Comment by Fourmisain** [comment] 2021-03-13 14:00
Looks like the same issue as https://github.com/CorgiTaco/BYG/issues/295.

**Comment by CorgiTaco** [comment] 2021-03-15 04:45
Duplicate of #295

**Closed as completed by CorgiTaco** 2021-03-15 04:45 UTC
Labels: Bug Minor, Duplicate
