### ISSUE TITLE
[Bug]: Levitating buttons and not able to see Clover Patch when placed on the ground

### ISSUE THREAD

**Issue by Princikk** [CorgiTaco/BYG#875] opened 2022-07-25 18:19 UTC
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.0.120

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Bug Severity

Minor

### What happened?

Bug with levitating buttons and not able to see Clover Patch when placed on the ground

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9183833/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by twixstix** [comment] 2022-08-16 03:25
To make this a little more useful - the problems reported are that buttons float above their hitbox when unpressed:
![2022-08-15_19 58 32](https://user-images.githubusercontent.com/28713862/184790759-f105ca27-a105-4f78-a4ae-5833d9f28c7d.png)

And flat blocks such as clovers, foliage, and flower patches appear to have issues aligning with their hitboxes as well as rotated variants not appearing:
![2022-08-15_19 59 15](https://user-images.githubusercontent.com/28713862/184790771-9ca5cad4-090a-46fc-a012-ecd9000ecea5.png)

I'm pretty sure the button problem is caused by the blockstate files calling for the inventory model rather than the basic one.

**Comment by CorgiTaco** [comment] 2022-10-10 07:25
I don't have any issues with buttons on latest 1.19 fabric: 

https://user-images.githubusercontent.com/66983020/194816240-c7eab9e1-588a-47f7-b490-ea537a6efeaa.mp4

**Comment by Tomatobird8** [comment] 2022-12-11 20:58
![2022-12-11_22 47 13](https://user-images.githubusercontent.com/60841151/206928150-930344b2-2b19-45df-b7ec-2a3b89e2b664.png)
![image](https://user-images.githubusercontent.com/60841151/206928398-c95ac721-1254-46db-bb9d-56e50a1cefed.png)
Incorrectly positioned/invisible clover patches on latest version

**Comment by YaBoiChips** [comment] 2022-12-18 04:12
will be fixed in latest version

**Closed as completed by YaBoiChips** 2022-12-18 04:12 UTC
Labels: Fabric, Bug, 1.19
