### ISSUE TITLE
[1.19][Bug]: Biomes not spawning in nether and end

### ISSUE THREAD

**Issue by gregest** [CorgiTaco/BYG#1265] opened 2023-10-18 10:42 UTC
### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4.jar

### Terrablender Version

TerraBlender-fabric-1.19.2-2.0.1.136.jar

### Mod Loader

Fabric

### Mod Loader Version

Fabric - 0.14.23

### Bug Severity

Major

### What happened?

The biomes in the Nether and End refuse to spawn or spawn in a very broken way, like missing trees. I originally thought that it was Amplified Nether and Nullscape which I have disabled and uninstalled, however that wasn't it. 

 The vanilla biomes and other modded biomes do spawn normally and the overworld biomes also spawn correctly.  

I checked the configs, everything that should be enabled is enabled and nothing is turned off, I also completely reset my configs by deleting them, deleting the mod and redownloading the mod

3 Images showing how the biomes that should be the biomes are just the default minecraft Hell biome. THIS is my modded profile
![javaw_2023-10-18_11-37-17](https://github.com/AOCAWOL/BYG/assets/56032903/380c241b-7cb0-4bf2-963f-430cf46627f2)
![javaw_2023-10-18_12-20-43](https://github.com/AOCAWOL/BYG/assets/56032903/78686798-3db4-49a5-8d3c-882364ba2282)
![javaw_2023-10-18_12-21-10](https://github.com/AOCAWOL/BYG/assets/56032903/918ff010-8ebe-46b1-8aae-7117e0cd06c4)
  

THIS is an entirely new profile with only fabric, BYG and roughly enough items to make it slightly easier to get to the nether, you can see that the biomes aren't bioming
![2023-10-18_12-34-41](https://github.com/AOCAWOL/BYG/assets/56032903/b45b05f7-5890-4fd4-b4d4-36e124f83239)
![javaw_2023-10-18_12-37-36](https://github.com/AOCAWOL/BYG/assets/56032903/5cc7c539-80d8-4a07-81fe-dd7901d3584c)
![javaw_2023-10-18_12-39-46](https://github.com/AOCAWOL/BYG/assets/56032903/7c727cd9-6516-4ca3-819d-9450ba659b6d)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/13011816/latest.log) THIS is the log of the CLEAN profile with only BYG  

[latest.log](https://github.com/AOCAWOL/BYG/files/13011869/latest.log) THIS is my MODDED profile with many other mods

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by AwesomeDude091** [comment] 2023-11-03 07:17
Was the world generated on a server instance, or a client instance?

**Comment by gregest** [comment] 2023-11-03 10:08
I would say client? I generated it myself on my pc in singleplayer    

but I actually found out that the issue was with terrablender specifically and not BYG, for some reason the version curse autodownloads is broken and had to use an older one

**Comment by AwesomeDude091** [comment] 2023-11-03 15:01
Thanks for getting back to me so quickly @gregest , I think I know where the issue originates. To confirm could you tell me if everything gets generated properly if you generate it with a Server Instance?

**Comment by gregest** [comment] 2023-11-03 16:39
I have no idea how to do that

**Comment by AwesomeDude091** [comment] 2023-11-03 16:57
Like start a server with the mod installed and then tell me if the world the server generates has the same flaw

**Comment by andriihorpenko** [comment] 2023-11-08 01:08
I am having the same issue and I'm running a server instance. However, I am running Forge, not Fabric. Do I fit here or should I create a separate issue?

**Comment by JT122406** [comment] 2023-11-11 02:47
Duplicate of #1259

**Comment by gregest** [comment] 2023-11-11 08:48
Ah, seems like I didn't do a good enough job at making sure it wasn't a duplicate, apologies. I finally got around to trying to mess with the server and just like the other guy, I wasn't able to

**Comment by JT122406** [comment] 2024-02-11 21:50
Nether will be redone in the future versions so I am closing this.

**Closed as completed by JT122406** 2024-02-11 21:50 UTC
Labels: Bug, 1.19
