### ISSUE TITLE
Version 1.1.5 not compatible with betterend

### ISSUE THREAD

**Issue by ZenoMetal** [CorgiTaco/BYG#296] opened 2021-02-11 08:48 UTC
__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

After updating to 1.1.5 Minecraft crashes and the log points at betterend, but after going back to 1.1.4 it works again

__**API/Modloader**__
Fabric

__**Describe the bug**__
After updating to 1.1.5 Minecraft crashes and the log points at betterend, but after going back to 1.1.4 it works again

__**To Reproduce**__
Update to newest BYG version

**Comment by CorgiTaco** [comment] 2021-02-11 09:01
3rd report about this in a row.... Duplicate of #294 & #293

**Closed as completed by CorgiTaco** 2021-02-11 09:01 UTC
Labels: Duplicate, Won't Fix, Fabric
