### ISSUE TITLE
[1.19][Bug]: Endermen are able to pick up ivis phylium

### ISSUE THREAD

**Issue by Rand0mN0ob** [CorgiTaco/BYG#1042] opened 2022-12-19 17:59 UTC
### BYG Version

2.0.0.13

### Terrablender Version

2.0.1.130

### Mod Loader

Forge

### Mod Loader Version

43.1.55

### Bug Severity

Minor

### What happened?

![image](https://user-images.githubusercontent.com/70676316/208489536-a0097261-4ae7-4fb7-98a5-2261c5c0f1ae.png)
endermen are able to pick up ivis phylium even though they cant pick up end stone normally.

### latest.log

https://gist.github.com/Rand0mN0ob/b8bc34e5e82ef7ceccde6245cb707461

### Did you isolate BYG?

I did not try BYG alone.

**Comment by Rand0mN0ob** [comment] 2022-12-19 18:00
Oops it wasnt alone it was in ATM 8 1.0.5

**Comment by Rand0mN0ob** [comment] 2022-12-19 18:00
Also severity is minor

**Comment by sciguyryan** [comment] 2023-01-30 12:13
The problem here is that ivis phylium is added into the minecraft:dirt tag list, which in turn is automatically included in the minecraft:enderman_holdable tag list.

https://github.com/AOCAWOL/BYG/blob/95d3efc45463320522549c08f537540fb9bd22ab/Forge/src/main/resources/data/forge/tags/blocks/dirt.json#L16

Actually, upon reflection, this would be a duplicate of #814 since it would be fixed by the commit in that bug.

**Comment by CorgiTaco** [comment] 2023-02-01 20:56
FIxed in https://github.com/AOCAWOL/BYG/commit/b4cc7fe4e27ce4a50c983a0dc6c64ab4ba247b7c

**Closed as completed by CorgiTaco** 2023-02-01 20:56 UTC
Labels: Bug, 1.19
