### ISSUE TITLE
Potted plants have missing texture

### ISSUE THREAD

**Issue by Brun333rp** [CorgiTaco/BYG#250] opened 2021-01-15 18:45 UTC
Trying to place any plant from BYG in a Flower Pot results in a missing texture. that's not a mod or resourcepack conflict, I tested it.

**Comment by CorgiTaco** [comment] 2021-01-15 18:45
Duplicate of #179

**Closed as completed by CorgiTaco** 2021-01-15 18:45 UTC
Labels: Duplicate

**Comment by Brun333rp** [comment] 2021-01-15 18:47
oh, sorry about this
