### ISSUE TITLE
[1.19][Bug]: Hates ReTerraForged (A continuation of TerraForged for 1.19x).

### ISSUE THREAD

**Issue by MagmaSlime123** [CorgiTaco/BYG#1253] opened 2023-09-26 20:27 UTC
### BYG Version

Oh_The_Biomes_You'll_Go-forge-1.19.4-4.0.0.2

### Terrablender Version

TerraBlender-forge-1.19.4-2.2.0.168

### Mod Loader

Forge

### Mod Loader Version

45.2.0

### Bug Severity

Major

### What happened?

Game crashes when creating a world.

### latest.log

[debug.log](https://github.com/AOCAWOL/BYG/files/12731566/debug.log)
[latest.log](https://github.com/AOCAWOL/BYG/files/12731569/latest.log)
[crash-2023-09-26_14.26.57-server.txt](https://github.com/AOCAWOL/BYG/files/12731585/crash-2023-09-26_14.26.57-server.txt)

Not many mods are being used here, but with BYG, Corgi/GekoLib, the game crashes. I also tried without BOP. Same issue.

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by equalizer32** [comment] 2023-09-27 15:36
The version of ReTerraForged you are using is incompatible with TerraBlender. Close this issue as it's not caused by BYG.

**Comment by MagmaSlime123** [comment] 2023-09-27 20:24
They do not support 1.19.4, which BYG is currently on.

**Closed as completed** 2023-10-11 02:03 UTC
Labels: Bug, 1.19
